In [ ]:
text = 'Hi Everyone! This is Hackers Realm. We are learning Natural Language Processing. We reached 1000000 views.'

In [ ]:
text.split('')

['Hi',
 'Everyone!',
 'This',
 'is',
 'Hackers',
 'Realm.',
 'We',
 'are',
 'learning',
 'Natural',
 'Language',
 'Processing.',
 'We',
 'reached',
 '1000000',
 'views.']

In [ ]:
from nltk import sent_tokenize, word_tokenize

In [ ]:
import nltk
nltk.download('punkt')

from nltk import sent_tokenize, word_tokenize

text = 'Hi Everyone! This is Hackers Realm. We are learning Natural Language Processing. We reached 1000000 views.'

sent_tokens = sent_tokenize(text)
sent_tokens

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


['Hi Everyone!',
 'This is Hackers Realm.',
 'We are learning Natural Language Processing.',
 'We reached 1000000 views.']

In [ ]:
# split the text into words
word_tokens = word_tokenize(text)
word_tokens

['Hi',
 'Everyone',
 '!',
 'This',
 'is',
 'Hackers',
 'Realm',
 '.',
 'We',
 'are',
 'learning',
 'Natural',
 'Language',
 'Processing',
 '.',
 'We',
 'reached',
 '1000000',
 'views',
 '.']

In [ ]:
from nltk.stem import PorterStemmer, SnowballStemmer
ps = PorterStemmer()

In [ ]:
word = ('eats')
ps.stem(word)

'eat'

In [ ]:
word = ('eating')
ps.stem(word)

'eat'

In [ ]:
text = 'Hi Everyone! This is Hackers Realm. We are learning Natural Language Processing. We reached 1000000 views.'

In [ ]:
word_tokens = word_tokenize(text)


In [ ]:
stemmed_sentence = " ".join(ps.stem(word) for word in word_tokens)
stemmed_sentence

'hi everyon ! thi is hacker realm . we are learn natur languag process . we reach 1000000 view .'

In [ ]:
import nltk
nltk.download('wordnet')

from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

lemmatizer.lemmatize('workers')

[nltk_data] Downloading package wordnet to /root/nltk_data...


'worker'

In [ ]:
lemmatizer.lemmatize('words')

'word'

In [ ]:
lemmatizer.lemmatize('feet')


'foot'

In [ ]:
lemmatizer.lemmatize('stripes', 'v')

'strip'

In [ ]:
lemmatizer.lemmatize('stripes', 'n')

'stripe'

In [ ]:
text = 'Hi earningEveryone! This is Hackers Realm. We are l Natural Language Processing. We reached 1000000 views.'

In [ ]:
word_tokens = word_tokenize(text)

In [ ]:
lemmatized_sentence = " ".join(lemmatizer.lemmatize(word.lower()) for word in word_tokens)
lemmatized_sentence

'hi everyone ! this is hacker realm . we are learning natural language processing . we reached 1000000 view .'

In [ ]:
from nltk import pos_tag

In [ ]:
import nltk
nltk.download('averaged_perceptron_tagger')

from nltk import pos_tag

pos_tag(['fighting'])

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


[('fighting', 'VBG')]

In [ ]:
text = 'Hi Everyone! This is Hackers Realm. We are learning Natural Language Processing. We reached 1000000 views.'
word_tokens = word_tokenize(text)
pos_tag(word_tokens)

[('Hi', 'NNP'),
 ('Everyone', 'NN'),
 ('!', '.'),
 ('This', 'DT'),
 ('is', 'VBZ'),
 ('Hackers', 'NNP'),
 ('Realm', 'NNP'),
 ('.', '.'),
 ('We', 'PRP'),
 ('are', 'VBP'),
 ('learning', 'VBG'),
 ('Natural', 'NNP'),
 ('Language', 'NNP'),
 ('Processing', 'NNP'),
 ('.', '.'),
 ('We', 'PRP'),
 ('reached', 'VBD'),
 ('1000000', 'CD'),
 ('views', 'NNS'),
 ('.', '.')]

In [ ]:
import pandas as pd
import string
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [ ]:
name_column=['Sentiment','OriginalTweet','UserName']
df=pd.read_csv('/content/drive/MyDrive/Data sets/twitter_training.csv', encoding = 'latin1', names=name_column)
df

Sentiment  \
UserName ScreenName Location                         TweetAt   
3799     48751      London                        16-03-2020   
3800     48752      UK                            16-03-2020   
3801     48753      Vagabonds                     16-03-2020   
3802     48754      NaN                           16-03-2020   
...                                                      ...   
44951    89903      Wellington City, New Zealand  14-04-2020   
44952    89904      NaN                           14-04-2020   
44953    89905      NaN                           14-04-2020   
44954    89906      NaN                           14-04-2020   
44955    89907      i love you so much || he/him  14-04-2020   

                                                                                      OriginalTweet  \
UserName ScreenName Location                                                          OriginalTweet   
3799     48751      London                        @MeNyrbie @Phil_Gahan @Chrisitv https://t.co/i...   
3800     48752      UK                            advice Talk to your neighbours family to excha...   
3801     48753      Vagabonds                     Coronavirus Australia: Woolworths to give elde...   
3802     48754      NaN                           My food stock is not the only one which is emp...   
...                                                                                             ...   
44951    89903      Wellington City, New Zealand  Airline pilots offering to stock supermarket s...   
44952    89904      NaN                           Response to complaint not provided citing COVI...   
44953    89905      NaN                           You know it’s getting tough when @KameronWild...   
44954    89906      NaN                           Is it wrong that the smell of hand sanitizer i...   
44955    89907      i love you so much || he/him  @TartiiCat Well new/used Rift S are going for ...   

                                                            UserName  
UserName ScreenName Location                               Sentiment  
3799     48751      London                                   Neutral  
3800     48752      UK                                      Positive  
3801     48753      Vagabonds                               Positive  
3802     48754      NaN                                     Positive  
...                                                              ...  
44951    89903      Wellington City, New Zealand             Neutral  
44952    89904      NaN                           Extremely Negative  
44953    89905      NaN                                     Positive  
44954    89906      NaN                                      Neutral  
44955    89907      i love you so much || he/him            Negative  

[41158 rows x 3 columns]

In [ ]:
df = df['Tweet content']

In [ ]:
df

0        im getting on borderlands and i will murder yo...
1        I am coming to the borders and I will kill you...
2        im getting on borderlands and i will kill you ...
3        im coming on borderlands and i will murder you...
4        im getting on borderlands 2 and i will murder ...
                               ...                        
74677    Just realized that the Windows partition of my...
74678    Just realized that my Mac window partition is ...
74679    Just realized the windows partition of my Mac ...
74680    Just realized between the windows partition of...
74681    Just like the windows partition of my Mac is l...
Name: Tweet content, Length: 74682, dtype: object

In [ ]:
import pandas as pd
import string

# Load the data, preserving the DataFrame structure
df = pd.read_csv('/content/twitter_training.csv', names=['id','entity','target','Tweet content'])

# Now you can access 'Tweet content' as a column
df['clean_text'] = df['Tweet content'].str.lower()
df.head()

id       entity    target  \
0  2401  Borderlands  Positive   
1  2401  Borderlands  Positive   
2  2401  Borderlands  Positive   
3  2401  Borderlands  Positive   
4  2401  Borderlands  Positive   

                                       Tweet content  \
0  im getting on borderlands and i will murder yo...   
1  I am coming to the borders and I will kill you...   
2  im getting on borderlands and i will kill you ...   
3  im coming on borderlands and i will murder you...   
4  im getting on borderlands 2 and i will murder ...   

                                          clean_text  
0  im getting on borderlands and i will murder yo...  
1  i am coming to the borders and i will kill you...  
2  im getting on borderlands and i will kill you ...  
3  im coming on borderlands and i will murder you...  
4  im getting on borderlands 2 and i will murder ...

In [ ]:
#Removal of Punctuations
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [ ]:
def remove_punctuations(text):
    punctuations = string.punctuation
    return text.translate(str.maketrans('', '', punctuations))

In [ ]:
import pandas as pd
import string

# Load the data, preserving the DataFrame structure
df = pd.read_csv('/content/twitter_training.csv', names=['id','entity','target','Tweet content'])

# Now you can access 'Tweet content' as a column
df['clean_text'] = df['Tweet content'].str.lower()

# Fill missing values in 'clean_text' with empty strings
df['clean_text'] = df['clean_text'].fillna('') # Fill NaNs to allow string operations

#Removal of Punctuations
string.punctuation

def remove_punctuations(text):
    punctuations = string.punctuation
    return text.translate(str.maketrans('', '', punctuations))

df['clean_text'] = df['clean_text'].apply(lambda x: remove_punctuations(x))
df.head()

id       entity    target  \
0  2401  Borderlands  Positive   
1  2401  Borderlands  Positive   
2  2401  Borderlands  Positive   
3  2401  Borderlands  Positive   
4  2401  Borderlands  Positive   

                                       Tweet content  \
0  im getting on borderlands and i will murder yo...   
1  I am coming to the borders and I will kill you...   
2  im getting on borderlands and i will kill you ...   
3  im coming on borderlands and i will murder you...   
4  im getting on borderlands 2 and i will murder ...   

                                          clean_text  
0  im getting on borderlands and i will murder yo...  
1  i am coming to the borders and i will kill you...  
2  im getting on borderlands and i will kill you all  
3  im coming on borderlands and i will murder you...  
4  im getting on borderlands 2 and i will murder ...

In [ ]:
import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords
", ".join(stopwords.words('english'))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


"i, me, my, myself, we, our, ours, ourselves, you, you're, you've, you'll, you'd, your, yours, yourself, yourselves, he, him, his, himself, she, she's, her, hers, herself, it, it's, its, itself, they, them, their, theirs, themselves, what, which, who, whom, this, that, that'll, these, those, am, is, are, was, were, be, been, being, have, has, had, having, do, does, did, doing, a, an, the, and, but, if, or, because, as, until, while, of, at, by, for, with, about, against, between, into, through, during, before, after, above, below, to, from, up, down, in, out, on, off, over, under, again, further, then, once, here, there, when, where, why, how, all, any, both, each, few, more, most, other, some, such, no, nor, not, only, own, same, so, than, too, very, s, t, can, will, just, don, don't, should, should've, now, d, ll, m, o, re, ve, y, ain, aren, aren't, couldn, couldn't, didn, didn't, doesn, doesn't, hadn, hadn't, hasn, hasn't, haven, haven't, isn, isn't, ma, mightn, mightn't, mustn, mus

In [ ]:
STOPWORDS = set(stopwords.words('english'))
def remove_stopwords(text):
    return " ".join([word for word in text.split() if word not in STOPWORDS])

In [ ]:
df['clean_text'] = df['clean_text'].apply(lambda x: remove_stopwords(x))
df.head()

id       entity    target  \
0  2401  Borderlands  Positive   
1  2401  Borderlands  Positive   
2  2401  Borderlands  Positive   
3  2401  Borderlands  Positive   
4  2401  Borderlands  Positive   

                                       Tweet content  \
0  im getting on borderlands and i will murder yo...   
1  I am coming to the borders and I will kill you...   
2  im getting on borderlands and i will kill you ...   
3  im coming on borderlands and i will murder you...   
4  im getting on borderlands 2 and i will murder ...   

                        clean_text  
0    im getting borderlands murder  
1              coming borders kill  
2      im getting borderlands kill  
3     im coming borderlands murder  
4  im getting borderlands 2 murder

In [ ]:
from collections import Counter
word_count = Counter()
for text in df['clean_text']:
    for word in text.split():
        word_count[word] += 1

word_count.most_common(10)

[('game', 8056),
 ('like', 4878),
 ('2', 4057),
 ('get', 3941),
 ('im', 3828),
 ('one', 3581),
 ('good', 3548),
 ('play', 3413),
 ('really', 3260),
 ('love', 3239)]

In [ ]:
FREQUENT_WORDS = set(word for (word, wc) in word_count.most_common(3))
def remove_freq_words(text):
    return " ".join([word for word in text.split() if word not in FREQUENT_WORDS])

In [ ]:
df['clean_text'] = df['clean_text'].apply(lambda x: remove_freq_words(x))
df.head()

id       entity    target  \
0  2401  Borderlands  Positive   
1  2401  Borderlands  Positive   
2  2401  Borderlands  Positive   
3  2401  Borderlands  Positive   
4  2401  Borderlands  Positive   

                                       Tweet content  \
0  im getting on borderlands and i will murder yo...   
1  I am coming to the borders and I will kill you...   
2  im getting on borderlands and i will kill you ...   
3  im coming on borderlands and i will murder you...   
4  im getting on borderlands 2 and i will murder ...   

                      clean_text  
0  im getting borderlands murder  
1            coming borders kill  
2    im getting borderlands kill  
3   im coming borderlands murder  
4  im getting borderlands murder

In [ ]:
RARE_WORDS = set(word for (word, wc) in word_count.most_common()[:-10:-1])
RARE_WORDS

{'challen',
 'doxmaxbitcc',
 'intend',
 'maxbit',
 'maxbitcc',
 'maxbitccnvidiadoesnt',
 'netcomgooglechallen',
 'nvidiadoes',
 'nvidiadoesnt'}

In [ ]:
def remove_rare_words(text):
    return " ".join([word for word in text.split() if word not in RARE_WORDS])

In [ ]:
df['clean_text'] = df['clean_text'].apply(lambda x: remove_rare_words(x))
df.head()


id       entity    target  \
0  2401  Borderlands  Positive   
1  2401  Borderlands  Positive   
2  2401  Borderlands  Positive   
3  2401  Borderlands  Positive   
4  2401  Borderlands  Positive   

                                       Tweet content  \
0  im getting on borderlands and i will murder yo...   
1  I am coming to the borders and I will kill you...   
2  im getting on borderlands and i will kill you ...   
3  im coming on borderlands and i will murder you...   
4  im getting on borderlands 2 and i will murder ...   

                      clean_text  
0  im getting borderlands murder  
1            coming borders kill  
2    im getting borderlands kill  
3   im coming borderlands murder  
4  im getting borderlands murder

In [ ]:
#Removal of Special characters

import re
def remove_spl_chars(text):
    text = re.sub('[^a-zA-Z0-9]', ' ', text)
    text = re.sub('\s+', ' ', text)
    return text

In [ ]:
df['clean_text'] = df['clean_text'].apply(lambda x: remove_spl_chars(x))
df.head()

id       entity    target  \
0  2401  Borderlands  Positive   
1  2401  Borderlands  Positive   
2  2401  Borderlands  Positive   
3  2401  Borderlands  Positive   
4  2401  Borderlands  Positive   

                                       Tweet content  \
0  im getting on borderlands and i will murder yo...   
1  I am coming to the borders and I will kill you...   
2  im getting on borderlands and i will kill you ...   
3  im coming on borderlands and i will murder you...   
4  im getting on borderlands 2 and i will murder ...   

                      clean_text  
0  im getting borderlands murder  
1            coming borders kill  
2    im getting borderlands kill  
3   im coming borderlands murder  
4  im getting borderlands murder

In [ ]:
#Stemming
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
def stem_words(text):
    return " ".join([ps.stem(word) for word in text.split()])

In [ ]:
df['stemmed_text'] = df['clean_text'].apply(lambda x: stem_words(x))
df.head()

id       entity    target  \
0  2401  Borderlands  Positive   
1  2401  Borderlands  Positive   
2  2401  Borderlands  Positive   
3  2401  Borderlands  Positive   
4  2401  Borderlands  Positive   

                                       Tweet content  \
0  im getting on borderlands and i will murder yo...   
1  I am coming to the borders and I will kill you...   
2  im getting on borderlands and i will kill you ...   
3  im coming on borderlands and i will murder you...   
4  im getting on borderlands 2 and i will murder ...   

                      clean_text               stemmed_text  
0  im getting borderlands murder   im get borderland murder  
1            coming borders kill           come border kill  
2    im getting borderlands kill     im get borderland kill  
3   im coming borderlands murder  im come borderland murder  
4  im getting borderlands murder   im get borderland murder

In [ ]:
#Lemmatization & POS Tagging

from nltk import pos_tag
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()
wordnet_map = {"N":wordnet.NOUN, "V": wordnet.VERB, "J": wordnet.ADJ, "R": wordnet.ADV}

def lemmatize_words(text):
    # find pos tags
    pos_text = pos_tag(text.split())
    return " ".join([lemmatizer.lemmatize(word, wordnet_map.get(pos[0], wordnet.NOUN)) for word, pos in pos_text])

In [ ]:
wordnet.NOUN

'n'

In [ ]:
df['lemmatized_text'] = df['clean_text'].apply(lambda x: lemmatize_words(x))
df.head()

id       entity    target  \
0  2401  Borderlands  Positive   
1  2401  Borderlands  Positive   
2  2401  Borderlands  Positive   
3  2401  Borderlands  Positive   
4  2401  Borderlands  Positive   

                                       Tweet content  \
0  im getting on borderlands and i will murder yo...   
1  I am coming to the borders and I will kill you...   
2  im getting on borderlands and i will kill you ...   
3  im coming on borderlands and i will murder you...   
4  im getting on borderlands 2 and i will murder ...   

                      clean_text               stemmed_text  \
0  im getting borderlands murder   im get borderland murder   
1            coming borders kill           come border kill   
2    im getting borderlands kill     im get borderland kill   
3   im coming borderlands murder  im come borderland murder   
4  im getting borderlands murder   im get borderland murder   

             lemmatized_text  
0   im get borderland murder  
1           come border kill  
2     im get borderland kill  
3  im come borderland murder  
4   im get borderland murder

In [ ]:
#Removal of URLs
text = "https://www.hackersrealm.net is the URL of the channel Hackers Realm"
def remove_url(text):
    return re.sub(r'https?://\S+|www\.\S+', '', text)
remove_url(text)

' is the URL of the channel Hackers Realm'

In [ ]:
#Removal of HTML Tags
text = "<html><body> <h1>Hackers Realm</h1> <p>This is NLP text preprocessing tutorial</p> </body></html>"
def remove_html_tags(text):
    return re.sub(r'<.*?>', '', text)
remove_html_tags(text)

' Hackers Realm This is NLP text preprocessing tutorial '

In [ ]:
#Spelling Correction
!pip install pyspellchecker
text = 'natur is a beuty'
from spellchecker import SpellChecker
spell = SpellChecker()

def correct_spellings(text):
    corrected_text = []
    misspelled_text = spell.unknown(text.split())
    # print(misspelled_text)
    for word in text.split():
        if word in misspelled_text:
            corrected_text.append(spell.correction(word))
        else:
            corrected_text.append(word)

    return " ".join(corrected_text)
correct_spellings(text)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.8/6.8 MB 39.3 MB/s eta 0:00:00


'nature is a beauty'

In [ ]:
#Bag of Words
#A bag-of-words is a representation of text that describes the occurrence of words within a document. It involves two things: A vocabulary of known words. A measure of the presence of known words.

text_data = ['I am interested in NLP', 'This is a good tutorial with good topic', 'Feature extraction is very important topic']
from sklearn.feature_extraction.text import CountVectorizer
bow = CountVectorizer(stop_words='english')
# fit the data
bow.fit(text_data)
CountVectorizer(stop_words='english')


CountVectorizer(stop_words='english')

In [ ]:
bow.get_feature_names_out()

array(['extraction', 'feature', 'good', 'important', 'interested', 'nlp',
       'topic', 'tutorial'], dtype=object)

In [ ]:
bow_features = bow.transform(text_data)
bow_features

<3x8 sparse matrix of type '<class 'numpy.int64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [ ]:
bow_feature_array = bow_features.toarray()
bow_feature_array

array([[0, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 2, 0, 0, 0, 1, 1],
       [1, 1, 0, 1, 0, 0, 1, 0]])

In [ ]:
print(bow.get_feature_names_out())
for sentence, feature in zip(text_data, bow_feature_array):
    print(sentence)
    print(feature)

['extraction' 'feature' 'good' 'important' 'interested' 'nlp' 'topic'
 'tutorial']
I am interested in NLP
[0 0 0 0 1 1 0 0]
This is a good tutorial with good topic
[0 0 2 0 0 0 1 1]
Feature extraction is very important topic
[1 1 0 1 0 0 1 0]


In [ ]:
#TF-IDF (Term Frequency/Inverse Document Frequency)
#TF-IDF stands for term frequency-inverse document frequency and it is a measure, used in the fields of information retrieval (IR) and machine learning, that can quantify the importance or relevance of string representations (words, phrases, lemmas, etc) in a document amongst a collection of documents

text_data = ['I am interested in NLP', 'This is a good tutorial with good topic', 'Feature extraction is very important topic']
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(stop_words='english')
# fit the data
tfidf.fit(text_data)
TfidfVectorizer(stop_words='english')
# get the vocabulary list
tfidf.vocabulary_

{'interested': 4,
 'nlp': 5,
 'good': 2,
 'tutorial': 7,
 'topic': 6,
 'feature': 1,
 'extraction': 0,
 'important': 3}

In [ ]:
tfidf_features = tfidf.transform(text_data)
tfidf_features

<3x8 sparse matrix of type '<class 'numpy.float64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [ ]:
tfidf_feature_array = tfidf_features.toarray()
tfidf_feature_array

array([[0.        , 0.        , 0.        , 0.        , 0.70710678,
        0.70710678, 0.        , 0.        ],
       [0.        , 0.        , 0.84678897, 0.        , 0.        ,
        0.        , 0.32200242, 0.42339448],
       [0.52863461, 0.52863461, 0.        , 0.52863461, 0.        ,
        0.        , 0.40204024, 0.        ]])

In [ ]:
for sentence, feature in zip(text_data, tfidf_features):
    print(sentence)
    print(feature)

I am interested in NLP
  (0, 5)	0.7071067811865476
  (0, 4)	0.7071067811865476
This is a good tutorial with good topic
  (0, 7)	0.42339448341195934
  (0, 6)	0.3220024178194947
  (0, 2)	0.8467889668239187
Feature extraction is very important topic
  (0, 6)	0.4020402441612698
  (0, 3)	0.5286346066596935
  (0, 1)	0.5286346066596935
  (0, 0)	0.5286346066596935
